export default {
  index: 'Overview',
  s3: 'S3',
  lambda: 'Lambda',
  dynamodb: 'DynamoDB',
  rds: 'RDS',
  apigateway: 'API Gateway',
  cloudfront: 'CloudFront',
  route53: 'Route53',
  acm: 'ACM',
  cognito: 'Cognito',
  ecs: 'ECS',
  ecr: 'ECR',
  sqs: 'SQS',
  sns: 'SNS',
  eventbridge: 'EventBridge',
  stepfunctions: 'Step Functions',
  kinesis: 'Kinesis',
  firehose: 'Data Firehose',
  glue: 'Glue',
  athena: 'Athena'
}
